name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install CUDA
      uses: Jimver/cuda-toolkit@v0.2.16

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Run Benchmarks
      working-directory: ${{github.workspace}}/build/${{env.BUILD_TYPE}}
      run: .\Benchmarks.exe > benchmarks.txt

    - name: Upload Benchmark Results
      uses: actions/upload-artifact@v3
      with:
        name: Benchmarks
        path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/benchmarks.txt