name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install CUDA
      uses: Jimver/cuda-toolkit@v0.2.16

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      uses: threeal/cmake-action@v2.0.0
      with:
        source-dir: ${{github.workspace}}
        build-dir: ${{github.workspace}}/build
        build-args: --config ${{env.BUILD_TYPE}}
        options: |
          RAPIDJSON_BUILD_DOC=OFF
          RAPIDJSON_BUILD_TESTS=OFF
          RAPIDJSON_BUILD_EXAMPLES=OFF
          BENCHMARK_INSTALL_DOCS=OFF
          BENCHMARK_ENABLE_TESTING=OFF

    - name: Benchmark
      working-directory: ${{github.workspace}}/build/${{env.BUILD_TYPE}}
      run: Benchmarks.exe